name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['*', 'lts/*']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests and collect coverage
        run: npm run test -- --coverage
      - name: Run build
        run: npm run build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
